import { useCallback, useEffect, useMemo, useState } from 'react'
import { useSyncExternalStore } from 'react'
import { Link, Navigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { MessageCircle, CheckCircle2, Share2, RefreshCw } from 'lucide-react'
import {
  listUnsettledDebts,
  settleDebtsForTransfer,
  settleAllDebtsInGroup,
} from '../lib/hisaabFirestore'
import { isDemoMode } from '../lib/demoMode'
import { subscribeDemo, getDemoSnapshot, demoSettleDebtsForTransfer, demoSettleAllDebtsInGroup } from '../demo/demoStore'
import { useAuth } from '../hooks/useAuth'
import { useGroup } from '../hooks/useGroup'
import { PageWrapper } from '../components/layout/PageWrapper'
import { Avatar } from '../components/ui/Avatar'
import { useToast } from '../context/ToastContext'
import { calculateSettlement, totalPaiseFromTransfers } from '../utils/settlement'
import { formatRsLabel } from '../utils/formatters'

export default function Settlement() {
  const { session, user } = useAuth()
  const { showToast } = useToast()
  const { activeGroupId, members } = useGroup(user?.id)
  const demoSnap = useSyncExternalStore(
    isDemoMode() ? subscribeDemo : () => () => {},
    isDemoMode() ? getDemoSnapshot : () => ({ debts: [] }),
    isDemoMode() ? getDemoSnapshot : () => ({ debts: [] })
  )
  const [debts, setDebts] = useState([])
  const [loading, setLoading] = useState(true)
  const [settling, setSettling] = useState(new Set())
  const [done, setDone] = useState(new Set())

  const load = useCallback(async () => {
    if (!activeGroupId) {
      setLoading(false)
      return
    }
    setLoading(true)
    if (isDemoMode()) {
      const rows = demoSnap.debts.filter((d) => d.group_id === activeGroupId && !d.settled)
      setDebts(rows)
      setLoading(false)
      return
    }
    try {
      const data = await listUnsettledDebts(activeGroupId)
      setDebts(data ?? [])
    } catch {
      setDebts([])
    }
    setLoading(false)
  }, [activeGroupId, demoSnap])

  useEffect(() => {
    load()
  }, [load])

  const transfers = useMemo(() => calculateSettlement(debts), [debts])
  const total = totalPaiseFromTransfers(transfers)

  const byId = useMemo(
    () => Object.fromEntries((members ?? []).map((m) => [m.id, m])),
    [members]
  )

  const monthLabel = new Date().toLocaleString('en-PK', {
    month: 'long',
    year: 'numeric',
  })

  if (!session) return <Navigate to="/" replace />

  // Mark ALL debts between t.from → t.to as settled in the database
  async function markPaid(idx, t) {
    if (settling.has(idx) || done.has(idx)) return
    setSettling((s) => new Set(s).add(idx))

    if (isDemoMode()) {
      demoSettleDebtsForTransfer(activeGroupId, t.from, t.to, true)
      setSettling((s) => {
        const n = new Set(s)
        n.delete(idx)
        return n
      })
      setDone((s) => new Set(s).add(idx))
      load()
      showToast(`${byId[t.from]?.name ?? 'Settled'} ✓ Hisaab clear!`)
      return
    }

    try {
      await settleDebtsForTransfer(activeGroupId, t.from, t.to, new Date().toISOString())
    } catch (error) {
      showToast(error?.message ?? 'Update failed', 'error')
      setSettling((s) => {
        const n = new Set(s)
        n.delete(idx)
        return n
      })
      return
    }

    setSettling((s) => {
      const n = new Set(s)
      n.delete(idx)
      return n
    })

    setDone((s) => new Set(s).add(idx))
    setDebts((prev) =>
      prev.map((d) =>
        d.ower_id === t.from && d.owed_to_id === t.to ? { ...d, settled: true } : d
      )
    )
    showToast(`${byId[t.from]?.name ?? 'Settled'} ✓ Hisaab clear!`)
  }

  async function markAllPaid() {
    if (!activeGroupId || transfers.length === 0) return
    if (isDemoMode()) {
      demoSettleAllDebtsInGroup(activeGroupId)
      showToast('All balances settled successfully.')
      setDone(new Set(transfers.map((_, i) => i)))
      setDebts([])
      load()
      return
    }
    try {
      await settleAllDebtsInGroup(activeGroupId, new Date().toISOString())
      showToast('All balances settled successfully.')
      setDone(new Set(transfers.map((_, i) => i)))
      setDebts([])
    } catch (error) {
      showToast(error?.message ?? 'Could not settle', 'error')
    }
  }

  function shareText() {
    const visibleTransfers = transfers.filter((_, i) => !done.has(i))
    if (visibleTransfers.length === 0) {
      navigator.clipboard.writeText(`Hisaab — ${monthLabel}: All clear ✓`)
      showToast('Copied!')
      return
    }
    const lines = visibleTransfers.map(
      (t) =>
        `${byId[t.from]?.name ?? '?'} → ${byId[t.to]?.name ?? '?'}: ${formatRsLabel(t.amount_paise)}`
    )
    const body = [
      `Hisaab — ${monthLabel} Settlement`,
      '━━━━━━━━━━━━━━━━━━━━━',
      ...lines,
      '━━━━━━━━━━━━━━━━━━━━━',
      `Total: ${formatRsLabel(total)}`,
      'Generated by Hisaab ✓',
    ].join('\n')
    navigator.clipboard.writeText(body).then(() => showToast('Copied to clipboard!'))
  }

  function waOne(t) {
    const body = `${byId[t.from]?.name ?? 'Member'} → ${byId[t.to]?.name ?? '?'}: ${formatRsLabel(t.amount_paise)} — Hisaab settlement\n\nPlease settle this transfer.`
    window.open(`https://wa.me/?text=${encodeURIComponent(body)}`, '_blank')
  }

  const pendingTransfers = transfers.filter((_, i) => !done.has(i))
  const allDone = transfers.length > 0 && pendingTransfers.length === 0

  return (
    <PageWrapper showBottomNav>
      <div className="mb-4 flex items-center justify-between">
        <div>
          <h1 className="font-display text-lg font-semibold">Month-End Settlement</h1>
          <p className="text-xs text-[var(--text-secondary)]">{monthLabel}</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            className="btn-ghost p-2 text-xs"
            onClick={load}
            title="Refresh"
          >
            <RefreshCw className="h-4 w-4" />
          </button>
          <Link to="/dashboard" className="text-sm text-[var(--accent)]">
            Home
          </Link>
        </div>
      </div>

      {loading ? (
        <div className="space-y-3">
          {[1, 2, 3].map((i) => (
            <div key={i} className="skeleton h-20 w-full" />
          ))}
        </div>
      ) : allDone ? (
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="card flex flex-col items-center py-12 text-center"
        >
          <CheckCircle2 className="h-12 w-12 text-[var(--success)]" />
          <h2 className="mt-4 font-display text-xl font-bold">All Clear! 🎉</h2>
          <p className="mt-2 text-sm text-[var(--text-secondary)]">
            All balances for this month have been settled.
          </p>
        </motion.div>
      ) : transfers.length === 0 ? (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="card flex flex-col items-center py-12 text-center"
        >
          <CheckCircle2 className="h-12 w-12 text-[var(--success)]" />
          <h2 className="mt-4 font-display text-xl font-bold">No Outstanding Debts 🎉</h2>
          <p className="mt-2 text-sm text-[var(--text-secondary)]">
            All shared expenses are already settled.
          </p>
        </motion.div>
      ) : (
        <>
          {/* Summary card */}
          <div className="card mb-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-[var(--text-secondary)] uppercase tracking-wide">
                  Minimum Transfers Needed
                </p>
                <p className="balance-number mt-1">{pendingTransfers.length}</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-[var(--text-secondary)] uppercase tracking-wide">
                  Total Amount
                </p>
                <p className="font-display text-lg font-bold mt-1">
                  {formatRsLabel(total)}
                </p>
              </div>
            </div>
            <p className="mt-3 text-xs text-[var(--text-muted)]">
              Transfers are optimized to minimize the number of payments.
            </p>
          </div>

          <div className="space-y-3">
            {transfers.map((t, i) => {
              const isDone = done.has(i)
              const isSettling = settling.has(i)
              const fromProfile = byId[t.from]
              const toProfile = byId[t.to]

              return (
                <motion.div
                  key={`${t.from}-${t.to}-${i}`}
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.06 }}
                  className={`card transition-all duration-300 ${
                    isDone
                      ? 'border-emerald-500/40 bg-emerald-500/5'
                      : 'hover:border-[var(--border-accent)]'
                  }`}
                >
                  {/* Transfer header */}
                  <div className="flex items-center gap-2">
                    <Avatar name={fromProfile?.name} color={fromProfile?.avatar_color} size="sm" />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">
                        {fromProfile?.name ?? 'Member'}
                      </p>
                      <p className="text-xs text-[var(--text-muted)]">pays</p>
                    </div>
                    <div className="text-center px-2">
                      <p className="font-display font-bold text-[var(--accent)]">
                        {formatRsLabel(t.amount_paise)}
                      </p>
                      <p className="text-xs text-[var(--text-muted)]">→</p>
                    </div>
                    <div className="flex-1 min-w-0 text-right">
                      <p className="text-sm font-medium truncate">
                        {toProfile?.name ?? 'Member'}
                      </p>
                      <p className="text-xs text-[var(--text-muted)]">receives</p>
                    </div>
                    <Avatar name={toProfile?.name} color={toProfile?.avatar_color} size="sm" />
                  </div>

                  {/* Actions */}
                  {isDone ? (
                    <div className="mt-3 flex items-center gap-2 text-emerald-400">
                      <CheckCircle2 className="h-4 w-4" />
                      <span className="text-sm font-medium">Settled ✓</span>
                    </div>
                  ) : (
                    <div className="mt-4 flex gap-2">
                      <button
                        type="button"
                        className="btn-ghost flex-1 py-2 text-xs"
                        onClick={() => waOne(t)}
                      >
                        <MessageCircle className="h-4 w-4" />
                        Remind
                      </button>
                      <button
                        type="button"
                        className="btn-primary flex-1 py-2 text-xs"
                        onClick={() => markPaid(i, t)}
                        disabled={isSettling}
                      >
                        {isSettling ? '...' : 'Mark Paid ✓'}
                      </button>
                    </div>
                  )}
                </motion.div>
              )
            })}
          </div>

          {/* Bottom actions */}
          <div className="mt-8 flex gap-3">
            <button
              type="button"
              className="btn-ghost flex-1 py-3"
              onClick={shareText}
            >
              <Share2 className="h-4 w-4" />
              Share
            </button>
            {pendingTransfers.length > 1 ? (
              <button
                type="button"
                className="btn-primary flex-1 py-3"
                onClick={markAllPaid}
              >
                Mark All Paid ✓
              </button>
            ) : null}
          </div>
        </>
      )}

    </PageWrapper>
  )
}
