import { jsPDF } from 'jspdf'

export function generateReceipt({ userName, amount_rupees, groupName, date, receiptId }) {
  const doc = new jsPDF()
  doc.setFillColor(12, 15, 26)
  doc.rect(0, 0, 210, 297, 'F')

  doc.setDrawColor(79, 110, 247)
  doc.setLineWidth(2)
  doc.line(20, 40, 190, 40)

  doc.setTextColor(248, 250, 252)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(28)
  doc.text('HISAAB', 20, 28)

  doc.setFontSize(11)
  doc.setTextColor(148, 163, 184)
  doc.text('Hisaab — Group Expense Receipt', 20, 36)

  const fields = [
    ['Contributor', userName],
    ['Group', groupName],
    ['Amount', `Rs ${Number(amount_rupees).toLocaleString('en-PK')}`],
    ['Date', date],
    ['Receipt ID', receiptId],
  ]

  let y = 56
  doc.setFontSize(12)
  fields.forEach(([label, value]) => {
    doc.setTextColor(148, 163, 184)
    doc.setFont('helvetica', 'normal')
    doc.text(label, 20, y)
    doc.setTextColor(248, 250, 252)
    doc.setFont('helvetica', 'bold')
    doc.text(String(value), 20, y + 7)
    y += 22
  })

  doc.setFontSize(9)
  doc.setTextColor(71, 85, 105)
  doc.text('Generated by Hisaab — Micathon 26', 20, 280)

  doc.save(`hisaab-receipt-${receiptId}.pdf`)
}
